(ns uiexplorer.react-requires)

; react-native
(set! js/ReactNative (js/require "react-native"))
(defonce Modal (.-Modal js/ReactNative))
(defonce Animated ^js/ReactNative.Animated (.-Animated js/ReactNative))
(defonce AnimatedValue ^js/ReactNative.Animated.Value (.-Value Animated))
(defonce AnimatedImage (aget Animated "Image"))
(defonce Dimensions (aget js/ReactNative "Dimensions"))
(defonce ListView (aget js/ReactNative "ListView"))
(defonce DataSource (aget ListView "DataSource"))
(defonce Image (aget js/ReactNative "Image"))
(defonce AppRegistry (aget js/ReactNative "AppRegistry"))
(defonce InteractionManager (aget js/ReactNative "InteractionManager"))
(defonce Platform (aget js/ReactNative "Platform"))
(defonce Linking (aget js/ReactNative "Linking"))
(defonce LayoutAnimation (aget js/ReactNative "LayoutAnimation"))
(defonce Keyboard (aget js/ReactNative "Keyboard"))
(defonce KeyboardAvoidingView (aget js/ReactNative "KeyboardAvoidingView"))
(defonce Picker (aget js/ReactNative "Picker"))
(defonce PickerItem (aget Picker "Item"))
(defonce Text (aget js/ReactNative "Text"))
(defonce TextInput (aget js/ReactNative "TextInput"))
(defonce Button (aget js/ReactNative "Button"))
(defonce View (aget js/ReactNative "View"))
(defonce ScrollView (aget js/ReactNative "ScrollView"))
(defonce Image (aget js/ReactNative "Image"))
(defonce AnimatedImage (aget js/ReactNative "AnimatedImage"))
(defonce TouchableOpacity (aget js/ReactNative "TouchableOpacity"))
(defonce TouchableHighlight (aget js/ReactNative "TouchableHighlight"))
(defonce AsyncStorage (aget js/ReactNative "AsyncStorage"))
(defonce ListView (aget js/ReactNative "ListView"))
(defonce TouchableOpacity (aget js/ReactNative "TouchableOpacity"))
(defonce Alert (aget js/ReactNative "Alert"))
(defonce AppState ^js/ReactNative.AppState (.-AppState js/ReactNative))
(defonce ActivityIndicator (aget js/ReactNative "ActivityIndicator"))
(defonce VirtualizedList (.-VirtualizedList js/ReactNative))
(defonce DatePickerIOS (aget js/ReactNative "DatePickerIOS"))
(defonce DatePickerAndroid (aget js/ReactNative "DatePickerAndroid"))

; react-native-vector-icons
(defonce Ionicons (aget (js/require "react-native-vector-icons/Ionicons") "default"))
